title: Blobtools
description: A modular command-line solution for visualisation, quality control and taxonomic partitioning of genome datasets
google_analytics: 
show_downloads: true
theme: jekyll-theme-slate

gems:
  - jekyll-mentions
